[border routing] add docker test for NCP

diff --git a/tests/scripts/ncp_mode b/tests/scripts/ncp_mode
--- a/tests/scripts/ncp_mode
+++ b/tests/scripts/ncp_mode
@@ -125,14 +125,30 @@ readonly CHILD_NODE_ID
 TUN_NAME=wpan0
 readonly TUN_NAME
 
+# OTBR docker image name
+OTBR_DOCKER_IMAGE=otbr-ncp
+readonly OTBR_DOCKER_IMAGE
+
 #----------------------------------------
 # Test steps
 #----------------------------------------
 build_ot_simulation()
 {
-    "${ABS_TOP_OT_SRCDIR}"/script/cmake-build simulation -DOT_MTD=OFF
-    ot_cli=$(find "${ABS_TOP_OT_BUILDDIR}" -name "${OT_CLI}")
-    ot_ncp=$(find "${ABS_TOP_OT_BUILDDIR}" -name "${OT_NCP}")
+    OT_CMAKE_BUILD_DIR=${ABS_TOP_OT_BUILDDIR}/ncp "${ABS_TOP_OT_SRCDIR}"/script/cmake-build simulation -DOT_MTD=OFF -DOT_APP_CLI=OFF -DOT_APP_RCP=OFF -DOT_BORDER_ROUTING=ON -DOT_NCP_INFRA_IF=ON
+    OT_CMAKE_BUILD_DIR=${ABS_TOP_OT_BUILDDIR}/cli "${ABS_TOP_OT_SRCDIR}"/script/cmake-build simulation -DOT_MTD=OFF -DOT_APP_NCP=OFF -DOT_APP_RCP=OFF -DOT_RCP=OFF -DOT_BORDER_ROUTING=OFF -DOT_NCP_INFRA_IF=OFF
+}
+
+setup_infraif()
+{
+    if ! ip link show backbone1 >/dev/null 2>&1; then
+        echo "Creating backbone1 with Docker..."
+        docker network create --driver bridge --ipv6 --subnet 9101::/64 -o "com.docker.network.bridge.name"="backbone1" backbone1
+    else
+        echo "backbone1 already exists."
+    fi
+
+    sysctl -w net.ipv6.conf.backbone1.accept_ra=2
+    sysctl -w net.ipv6.conf.backbone1.accept_ra_rt_info_max_plen=64
 }
 
 test_setup()
@@ -146,7 +162,9 @@ test_setup()
     # OPENTHREAD_POSIX_DAEMON_SOCKET_LOCK
     sudo rm -vf "/tmp/openthread.lock"
 
-    build_ot_simulation
+    [ ${BUILD_OT_SIM} = 1 ] && build_ot_simulation
+    ot_cli=$(find "${ABS_TOP_OT_BUILDDIR}" -name "${OT_CLI}")
+    ot_ncp=$(find "${ABS_TOP_OT_BUILDDIR}" -name "${OT_NCP}")
 
     # We will be creating a lot of log information
     # Rotate logs so we have a clean and empty set of logs uncluttered with other stuff
@@ -160,6 +178,14 @@ test_setup()
 
     write_syslog "AGENT: kill old"
     sudo killall "${OTBR_AGENT}" || true
+
+    # Build otbr docker image
+    if [[ ${BUILD_OTBR_DOCKER} == 1 ]]; then
+        cd ${ABS_TOP_SRCDIR}
+        ./script/build_docker ${OTBR_DOCKER_IMAGE}
+    fi
+
+    setup_infraif
 
     # From now on - all exits are TRAPPED
     # When they occur, we call the function: output_logs'.
@@ -182,7 +208,6 @@ test_teardown()
     sudo rm /etc/dbus-1/system.d/otbr-agent.conf || true
     sudo rm -rf "${STAGE_DIR}" || true
     sudo rm -rf "${BUILD_DIR}" || true
-    sudo rm -rf "${ABS_TOP_OT_BUILDDIR}" || true
 
     exit_message="Test teardown"
     echo "EXIT ${EXIT_CODE}: MESSAGE: ${exit_message}"
@@ -208,7 +233,6 @@ otbr_exec_expect_script()
         } || {
             local EXIT_CODE=$?
 
-<<<<<<< HEAD:tests/scripts/ncp_mode
             echo -e "\n${OTBR_COLOR_FAIL}FAIL${OTBR_COLOR_NONE} ${script}"
             cat "${log_file}" >&2
             return "${EXIT_CODE}"
@@ -220,8 +244,41 @@ otbr_exec_expect_script()
     done
 }
 
+parse_args()
+{
+    BUILD_OT_SIM=1
+    BUILD_OTBR_DOCKER=1
+    RUN_ALL_TESTS=1
+
+    while [ $# -gt 0 ]; do
+        case $1 in
+            --build-ot-sim)
+                BUILD_OT_SIM="$2"
+                shift
+                shift
+                ;;
+            --build-otbr-docker)
+                BUILD_OTBR_DOCKER="$2"
+                shift
+                shift
+                ;;
+            --one-test)
+                RUN_ALL_TESTS=0
+                TEST_NAME="$2"
+                shift
+                shift
+                ;;
+            *)
+                shift
+                ;;
+        esac
+    done
+}
+
 main()
 {
+    parse_args "$@"
+
     test_setup
 
     export EXP_OTBR_AGENT_PATH="${OTBR_AGENT_PATH}"
@@ -229,13 +286,15 @@ main()
     export EXP_LEADER_NODE_ID="${LEADER_NODE_ID}"
     export EXP_OT_CLI_PATH="${ot_cli}"
     export EXP_OT_NCP_PATH="${ot_ncp}"
+    export EXP_OTBR_DOCKER_IMAGE="${OTBR_DOCKER_IMAGE}"
 
-    if [[ $# != 0 ]]; then
-        otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/$1" || die "ncp expect script failed!"
+    if [[ ${RUN_ALL_TESTS} == 0 ]]; then
+        otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/${TEST_NAME}" || die "ncp expect script failed!"
     else
         otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/ncp_version.exp" || die "ncp expect script failed!"
         otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/ncp_get_device_role.exp" || die "ncp expect script failed!"
         otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/ncp_join_leave.exp" || die "ncp expect script failed!"
+        otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/ncp_border_routing.exp" || die "ncp expect script failed!"
     fi
 }
 
