[controller] add schedule migration api

diff --git a/tests/scripts/thread_control_api b/tests/scripts/thread_control_api
--- a/tests/scripts/thread_control_api
+++ b/tests/scripts/thread_control_api
@@ -110,6 +110,8 @@ readonly OTBR_AGENT_PATH
 # The node ids
 LEADER_NODE_ID=1
 readonly LEADER_NODE_ID
+CHILD_NODE_ID=2
+readonly CHILD_NODE_ID
 
 # The TUN device for OpenThread border router.
 TUN_NAME=wpan0
@@ -120,7 +122,7 @@ readonly TUN_NAME
 #----------------------------------------
 build_ot_simulation()
 {
-    "${ABS_TOP_OT_SRCDIR}"/script/cmake-build simulation -DOT_APP_CLI=OFF -DOT_MTD=OFF
+    "${ABS_TOP_OT_SRCDIR}"/script/cmake-build simulation -DOT_MTD=OFF
     ot_cli=$(find "${ABS_TOP_OT_BUILDDIR}" -name "${OT_CLI}")
     ot_ncp=$(find "${ABS_TOP_OT_BUILDDIR}" -name "${OT_NCP}")
 }
@@ -131,6 +133,8 @@ test_setup()
 
     # Remove flashes
     sudo rm -vrf "${TEST_BASE}/tmp"
+    sudo mkdir -p "${TEST_BASE}/tmp"
+
     # OPENTHREAD_POSIX_DAEMON_SOCKET_LOCK
     sudo rm -vf "/tmp/openthread.lock"
 
@@ -204,26 +208,73 @@ otbr-agent_start()
     write_syslog "AGENT: start complete"
 }
 
+cli_start()
+{
+    local dataset="0e080000000000010000000300000c35060004001fffe00208b4fe648bc41d8fc40708fd014557fad5636805101ef3e789519728b8b0df721b89bab9b2030f4f70656e5468726561642d3363393601023c96041067c8a446a15bde3577b975d49dbeb2f20c0402a0f7f833080000000000010000340400006af9"
+    write_syslog 'Cli START'
+    cd ${TEST_BASE}
+    sudo expect -f- <<EOF || die 'Cli FAILED'
+spawn ${ot_cli} ${CHILD_NODE_ID}
+send "dataset set active ${dataset}\r\n"
+expect "Done"
+send "ifconfig up\r\n"
+expect "Done"
+send "thread start\r\n"
+expect "Done"
+sleep 10
+send "state\r\n"
+expect -re "router|child"
+expect "Done"
+send "networkname\r\n"
+expect "OpenThread-3c96"
+expect "Done"
+EOF
+    exit_message="Cli attach COMPLETE"
+}
+
 test_thread_control_apis()
 {
     sudo dbus-send --system --dest=io.openthread.BorderRouter.wpan0 --type=method_call --print-reply /io/openthread/BorderRouter/wpan0 org.freedesktop.DBus.Properties.Get string:io.openthread.BorderRouter string:DeviceRole | grep -E "disabled"
 
-    local dataset="0x0e,0x08,0x00,0x00,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x03,0x00,0x00,0x14,"
-    dataset+="0x35,0x06,0x00,0x04,0x00,0x1f,0xff,0xe0,0x02,0x08,0x7d,0x61,0xeb,0x42,0xcd,0xc4,"
-    dataset+="0x8d,0x6a,0x07,0x08,0xfd,0x0d,0x07,0xfc,0xa1,0xb9,0xf0,0x50,0x05,0x10,0xba,0x08,"
-    dataset+="0x8f,0xc2,0xbd,0x6c,0x3b,0x38,0x97,0xf7,0xa1,0x0f,0x58,0x26,0x3f,0xf3,0x03,0x0f,"
-    dataset+="0x4f,0x70,0x65,0x6e,0x54,0x68,0x72,0x65,0x61,0x64,0x2d,0x35,0x32,0x34,0x66,0x01,"
-    dataset+="0x02,0x52,0x4f,0x04,0x10,0x9d,0xc0,0x23,0xcc,0xd4,0x47,0xb1,0x2b,0x50,0x99,0x7e,"
-    dataset+="0xf6,0x80,0x20,0xf1,0x9e,0x0c,0x04,0x02,0xa0,0xf7,0xf8"
+    local dataset1="0x0e,0x08,0x00,0x00,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x03,0x00,0x00,0x14,"
+    dataset1+="0x35,0x06,0x00,0x04,0x00,0x1f,0xff,0xe0,0x02,0x08,0x7d,0x61,0xeb,0x42,0xcd,0xc4,"
+    dataset1+="0x8d,0x6a,0x07,0x08,0xfd,0x0d,0x07,0xfc,0xa1,0xb9,0xf0,0x50,0x05,0x10,0xba,0x08,"
+    dataset1+="0x8f,0xc2,0xbd,0x6c,0x3b,0x38,0x97,0xf7,0xa1,0x0f,0x58,0x26,0x3f,0xf3,0x03,0x0f,"
+    dataset1+="0x4f,0x70,0x65,0x6e,0x54,0x68,0x72,0x65,0x61,0x64,0x2d,0x35,0x32,0x34,0x66,0x01,"
+    dataset1+="0x02,0x52,0x4f,0x04,0x10,0x9d,0xc0,0x23,0xcc,0xd4,0x47,0xb1,0x2b,0x50,0x99,0x7e,"
+    dataset1+="0xf6,0x80,0x20,0xf1,0x9e,0x0c,0x04,0x02,0xa0,0xf7,0xf8"
 
     sudo dbus-send --system --dest=io.openthread.BorderRouter.wpan0 \
         --type=method_call --print-reply /io/openthread/BorderRouter/wpan0 \
-        io.openthread.BorderRouter.AttachAllNodesTo \
-        "array:byte:${dataset}"
+        io.openthread.BorderRouter.Join \
+        "array:byte:${dataset1}"
 
     sleep 10
 
     sudo dbus-send --system --dest=io.openthread.BorderRouter.wpan0 --type=method_call --print-reply /io/openthread/BorderRouter/wpan0 org.freedesktop.DBus.Properties.Get string:io.openthread.BorderRouter string:DeviceRole | grep -E "leader"
+
+    # Migrate to another network
+    # Delay: 30s
+    # Netowrk Name: OpenThread-3c96
+    local dataset2="0x0e,0x08,0x00,0x00,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x03,0x00,0x00,0x0c,"
+    dataset2+="0x35,0x06,0x00,0x04,0x00,0x1f,0xff,0xe0,0x02,0x08,0xb4,0xfe,0x64,0x8b,0xc4,0x1d,"
+    dataset2+="0x8f,0xc4,0x07,0x08,0xfd,0x01,0x45,0x57,0xfa,0xd5,0x63,0x68,0x05,0x10,0x1e,0xf3,"
+    dataset2+="0xe7,0x89,0x51,0x97,0x28,0xb8,0xb0,0xdf,0x72,0x1b,0x89,0xba,0xb9,0xb2,0x03,0x0f,"
+    dataset2+="0x4f,0x70,0x65,0x6e,0x54,0x68,0x72,0x65,0x61,0x64,0x2d,0x33,0x63,0x39,0x36,0x01,"
+    dataset2+="0x02,0x3c,0x96,0x04,0x10,0x67,0xc8,0xa4,0x46,0xa1,0x5b,0xde,0x35,0x77,0xb9,0x75,"
+    dataset2+="0xd4,0x9d,0xbe,0xb2,0xf2,0x0c,0x04,0x02,0xa0,0xf7,0xf8,0x33,0x08,0x00,0x00,0x00,"
+    dataset2+="0x00,0x00,0x01,0x00,0x00,0x34,0x04,0x00,0x00,0x6a,0xf9"
+
+    sudo dbus-send --system --dest=io.openthread.BorderRouter.wpan0 \
+        --type=method_call --print-reply /io/openthread/BorderRouter/wpan0 \
+        io.openthread.BorderRouter.AttachAllNodesTo \
+        "array:byte:${dataset2}"
+
+    sleep 31
+
+    # Use a cli to verify that the otbr migrates to the correct network
+    cli_start
+    sleep 3
 
     sudo dbus-send --system --dest=io.openthread.BorderRouter.wpan0 \
         --type=method_call --print-reply /io/openthread/BorderRouter/wpan0 \
